- hosts: db
  tasks: 

  - name: install Python
    yum: name=MySQL-Python state=installed

  - name: install mysql
    yum: name=mysql-community-release state=installed

  - name: install mysql-server
    yum: name=mysql-server state=installed

  - name: start my sql service
    service: name=mysqld state=restarted

  - name: create db
    become: yes
    mysql_db:
      login_user: root
      name: gogs
      encoding: utf8mb4_general_ci
      state: present
