- hosts: db
  tasks:

    - name: Install MySQL
      action: yum name={{ item }}
      with_items:
        - MySQL-python
        - mysql
        - mysql-server

    - name: Start the MySQL service
      action: service name=mysqld state=started

    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password=admin123 priv=*.*:ALL,GRANT
      with_items:
        - "db"
        - 127.0.0.1
        - ::1
        - localhost