- hosts: db
  tasks: 

#remove wget after test
  - name: install wget
    yum: name=wget state=installed

  - name: install Python
    become: yes
    yum: name=MySQL-python state=latest

  - name: download lib
    get_url: url=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm dest=~/mysql-community-release-el7-5.noarch.rpm

  - name: install rpm
    become: yes
    yum: name=mysql-community-release-el7-5.noarch.rpm state=present

  - name: install mysql
    become: yes
    yum: name=mysql-server state=installed

  - name: start my sql service
    become: yes
    service: name=mysqld state=restarted

  - name: create db
    become: yes
    mysql_db:
      login_user: root
      name: gogs
      state: present
