- hosts: db
  tasks: 

#remove wget after test
  - name: install wget
    yum: name=wget state=installed

  - name: install Python
    become: yes
    yum: name=MySQL-python state=latest

  - name: download lib
    get_url: url=http://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm dest=~/mysql80-community-release-el7-3.noarch.rpm

  - name: install rpm
    become: yes
    yum: name=mysql80-community-release-el7-3.noarch.rpm state=present

  - name: install mysql
    become: yes
    yum: name=mysql-server state=installed

  - name: start my sql service
    become: yes
    service: name=mysqld state=restarted

  - name: create db 
    become: yes
    mysql_db:
      login_user: root
      name: gogs
      state: present
      encoding: utf8mb4
    
  - name: change root password
    become: yes
    mysql_user:
      login_user: root
      name: root
      password: admin123

  - name: restart my sql service
    become: yes
    service: name=mysqld state=restarted