- hosts: all
  tasks:

  - name: change directory
    command: "cd /usr/local"

  - name: get archive
    command: "wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz"
  
  - name: extract archive
    command: "rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz"

  - name: add directory to PATH
    command: "export PATH=$PATH:/usr/local/go/bin"

