- hosts: all
  tasks:

  - name: get archive
    command: wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
    become: yes
    args:
      chdir: /usr/local

  - name: extract archive
    command: tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
    become: yes
    args:
      chdir: /usr/local


