- hosts: apps
  vars_files:
    - ~/Ansible/vars/vars.yml  
  tasks:
  
  - name: get archive
    get_url: url=https://go.dev/dl/{{ go_package }} dest=/usr/local/

  - name: extract archive
    command: tar -C /usr/local -xzf {{ go_package }}
    args:
      chdir: /usr/local


