 - hosts: apps
   vars_files:
    - ~/Ansible/vars/vars.yml
   tasks:

   - name: clone the repository
     command: git clone {{ git_repo }}
     args:
       chdir: /home

   - name: create a directory appdata
     ansible.builtin.file:
       path: '{{ app_path }}/appdata'
       state: directory
       mode: '0755'

   - name: generate app.ini
     template: src={{ source_template }}/app.ini dest={{ app_path }}/conf/app.ini mode=0775

   - name: build gogs
     args:
       chdir: "{{ app_path }}"
     environment:
       PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin
     command: go build -o gogs