- hosts: lb
  vars_files:
    - ~/Ansible/vars/vars.yml  
  tasks:

  - name: update packages
    yum: name=* state=latest

  - name: install epel
    yum: name=epel-release state=present

  - name: install nginx
    yum: name=nginx state=latest

  - name: generate lb.conf to nginx
    template: src={{ source_template }}/lb.conf dest={{ destination_lb }} mode=0555

  - name: start and enable nginx
    service:
       name: nginx
       enabled: yes
       state: started
