- hosts: all
  tasks: 
  
  - name: install Python
    become: yes
    yum: name=MySQL-python state=latest

  - name: download lib
    get_url: url=https://downloads.mariadb.com/MariaDB/mariadb_repo_setup dest=~/mariadb_repo_setup

  - name: chmod
    command: chmod +x mariadb_repo_setup

  - name: setup mariadb
    become: yes
    command: ./mariadb_repo_setup

  - name: install MariaDB
    become: yes
    command: name=mariadb-server state=latest

  - name: start mariadb
    become: yes
    service: name=mariadb enabled=true state=started

  - name: create db 
    become: yes
    mysql_db:
      login_user: root
      name: gogs
      state: present

  - name: change root password
    become: yes
    mysql_user:
      login_user: root
      name: root
      password: admin123