- hosts: apps
  vars_files:
   - ~/Ansible/vars/vars.yml
  tasks:

  - name: start the app
    command: ./gogs web
    args:
      chdir: "{{ app_path }}"
    environment:
      PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin